name: Release 
on:
  push:
    tags:
      - '*'   
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none
jobs:
  deploy:
    if: github.repository_owner == 'myridia'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2   
        
      - name: install via apt-get
        run: |
            sudo apt-get install wget unzip zip
            
      - name: zip domain-swapper
        run: |
          cd test/wordpress/wp-content/plugins/
          zip -r domain-translate.zip domain-translate 
         
      - name: release 
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'test/wordpress/wp-content/plugins/domain-translate.zip'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
