name: Publish Wordpress Plugin
on:
    push:
       tags:
        - "*"

jobs:
  build:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
              sudo apt-get install -y subversion
